### ISSUE TITLE
[Bug] Failed to download

### ISSUE THREAD

**Issue by tezrilet** [L4cache/kemono-dl#35]
### Version
Version: 2024.02.02

### Your Command

```bash
python3 /root/kemono-dl/kemono-dl.py --cookies /root/kemono-dl/cookies-kemono-party.txt --inline --content --comments --json --dms --icon --banner --dirname-pattern \"{username}\\{service}\" --filename-pattern \"[{id}] ({published}) {title}\\{filename}.{ext}\" --inline-filename-pattern \"[{id}] ({published}) {title}\other\inline\{filename}.{ext}\" --other-filename-pattern \"[{id}] ({published}) {title}\other\{filename}.{ext}\" --date-strf-pattern \"%Y-%m-%d\" --from-file download.txt --archive archive.txt
```
The `download.txt` contains URLs of posts, 1 per line.

### Description of bug
It's able to download the post, but some attachments result in an error. I have also tried giving full permissions (chmod 777) to the script, but that did not change anything.

### How To Reproduce
Run the above command. Only certain posts will produce the error, but it's rare.

### Error messages and tracebacks
```python
ERROR:Failed to download: <ommitted>
Traceback (most recent call last):
  File "/root/kemono-dl/src/main.py", line 429, in download_attachments
    self.download_file(file, retry=self.retry, postid=post['post_variables']['id'])
  File "/root/kemono-dl/src/main.py", line 597, in download_file
    with open(part_file, 'wb' if resume_size == 0 else 'ab') as f:
PermissionError: [Errno 1] Operation not permitted: '<ommitted>'
```

### Additional comments
I can provide specific URLs and full debug logs privately.

**Comment by L4cache** [comment]
I think I need the URLs and logs.
Is GPG ok?

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEZs4zahYJKwYBBAHaRw8BAQdA8TwApK1RLGHAdLsAFbdi4DEhbDsD1Lxn89GG
kjniOvK0B2w0Y2FjaGWImQQTFgoAQRYhBF3LLv/z9Yf1FdTgsqnTkFJ1QgqkBQJm
zjNqAhsDBQkFo5qABQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEKnTkFJ1
QgqkqtcA/jY2BI8g2Bc8Dp2tuYiDUVsUG1hJp3ik29EbLmMwEuk8AQCOmuKn9L3z
iSOnjuMIakkW1gAmSq5tTOpxwwUbkgzjArg4BGbOM2oSCisGAQQBl1UBBQEBB0C0
IIOa2bNBT1LGN5UGEgtVJaXyPpF2daGwh8hxF78bPwMBCAeIfgQYFgoAJhYhBF3L
Lv/z9Yf1FdTgsqnTkFJ1QgqkBQJmzjNqAhsMBQkFo5qAAAoJEKnTkFJ1QgqkKc8A
/iwfqpWqsQFkK4F3VwM5zOtghx5snedkc+FiiDNik6cmAP91OnNsiNeh0ZgWutmS
eHgGmb/L4xX8skCFOkPdqmSkDg==
=Vm3/
-----END PGP PUBLIC KEY BLOCK-----

**Comment by L4cache** [comment]
I got error when I tried to decrypt it, what happened? (I'm not very familiar with GPG)
```
$ gpg --output log.log --decrypt log.txt
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
```

**Comment by L4cache** [comment]
It is decryptable now. I have some idea but I'll have to inspect it later (won't be a very long time)

**Comment by L4cache** [comment]
I can't reproduce the error...
This problem is probably specific to your setup.
Can you elaborate on the environment you using? Assuming it's Linux, what distro are you using and what's the version of it? Are you using root user?

**Comment by L4cache** [comment]
I think the problem is due to the lack of Windows "long paths" support in your shared directory, or you didn't enable it in your host machine, the filename length is limited to 255 bytes which is fine by both Windows and Linux.
I tested the post you mentioned in Windows and Linux VMs and didn't reproduce the issue.

But Windows by default only allows the absolute path to be up to 256 characters (or 260, including the "D:\" thing and terminating null character), in Windows 10 1607 and above the system can be configured to extend that limitation, by 
 doing https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later or install python and the installer will prompt you to enable that (my prefered way LOL, I'll be using python anyways)
